spring.application.name=FloodAlerts

server.port=${SERVER_PORT:8080}

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/floodalerts}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Shamee2004@}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

# MongoDB (Flood Reports)
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/floodalerts}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# JWT
app.jwt.secret=${APP_JWT_SECRET:replace_with_a_long_secret_key_12345678901234567890}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}

# Logging
logging.level.root=INFO
logging.level.Atomic5.demo=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.data.mongodb.repositories.enabled=false
spring.main.allow-bean-definition-overriding=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration