spring.config.import=optional:file:.env[.properties]

spring.application.name=FloodAlerts

spring.datasource.url=jdbc:postgresql://localhost:5432/floodalerts
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

<<<<<<< HEAD
# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/floodalerts}

# JWT
app.jwt.secret=${APP_JWT_SECRET:replace_with_a_long_secret_key_12345678901234567890}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}

# Logging
logging.level.root=INFO
logging.level.Atomic5.demo=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.data.mongodb.repositories.enabled=false
spring.main.allow-bean-definition-overriding=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

server.forward-headers-strategy=framework
=======
>>>>>>> origin/main
